version: '3.8'

services:
  # MCP gRPC Server
  mcp-server:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    container_name: mcp-server
    restart: unless-stopped
    ports:
      - "50051:50051"
    volumes:
      - ./config:/app/config
      - ./certs:/app/certs
      - ./logs:/app/logs
      - ./traces:/app/traces
    environment:
      - MCP_SERVER_HOST=0.0.0.0
      - MCP_SERVER_PORT=50051
      - MCP_AUTH_TYPE=mtls
      - MCP_CERT_PATH=/app/certs/server.crt
      - MCP_KEY_PATH=/app/certs/server.key
      - MCP_CA_PATH=/app/certs/ca.crt
      - MCP_CONFIG_PATH=/app/config/server.yaml
      - MCP_LOG_LEVEL=INFO
      - TELEMETRY_ENABLED=true
      - TELEMETRY_EXPORTER=prometheus
    networks:
      - mcp-network
    healthcheck:
      test: ["CMD", "python", "-c", "import grpc; grpc.insecure_channel('localhost:50051').channel_ready()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Telemetry Dashboard
  dashboard:
    build:
      context: .
      dockerfile: docker/dashboard.Dockerfile
    container_name: mcp-dashboard
    restart: unless-stopped
    ports:
      - "8050:8050"
    volumes:
      - ./traces:/app/traces
      - ./logs:/app/logs
    environment:
      - DASH_DEBUG=false
      - DASH_REQUESTS_PATHNAME_PREFIX=/
      - TRACES_DIR=/app/traces
      - REFRESH_INTERVAL=5
      - LOG_LEVEL=INFO
    depends_on:
      - mcp-server
    networks:
      - mcp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8050/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - mcp-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Grafana for advanced visualization
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secure_password
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - mcp-network
    depends_on:
      - prometheus
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  mcp-network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
