name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    
    - name: Install dependencies
      run: |
        uv venv
        source .venv/bin/activate
        uv pip install -e ".[dev]"
    
    - name: Generate Protocol Buffer code
      run: |
        source .venv/bin/activate
        ./scripts/generate_protos.sh
    
    - name: Lint with flake8
      run: |
        source .venv/bin/activate
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    
    - name: Check formatting with black
      run: |
        source .venv/bin/activate
        black --check .
    
    - name: Check imports with isort
      run: |
        source .venv/bin/activate
        isort --check .
    
    - name: Type check with mypy
      run: |
        source .venv/bin/activate
        mypy secure_mcp_grpc
    
    - name: Test with pytest
      run: |
        source .venv/bin/activate
        pytest --cov=secure_mcp_grpc --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true

  build-docker:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build server image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./docker/server-uv.Dockerfile
        tags: secure-mcp-grpc-server:latest
        push: false
        cache-from: type=gha
        cache-to: type=gha,mode=max
        outputs: type=docker,dest=/tmp/server-image.tar
    
    - name: Build dashboard image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./docker/dashboard-uv.Dockerfile
        tags: secure-mcp-grpc-dashboard:latest
        push: false
        cache-from: type=gha
        cache-to: type=gha,mode=max
        outputs: type=docker,dest=/tmp/dashboard-image.tar
    
    - name: Test Docker Compose
      run: |
        docker-compose -f docker-compose-uv.yml config
